services:
  - type: web
    name: stockmarketapp
    env: python
    plan: free
    buildCommand: ./Backend/build.sh
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
