services:
  - type: web
    name: stockmarketapp
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
